# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'renogy_solar_booth' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Firebase/Core', '~> 5.10.0'
  pod 'GoogleAppMeasurement', '~> 5.2.0'
  pod 'Firebase/Firestore'

end
